name: CD - Terraform Deploy (manual)

on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: 'Docker image tag (e.g. full commit SHA)'
        required: true
        default: 'latest'
      docker_repo:
        description: 'Docker repo (username/strapi-app) — override if needed'
        required: false
        default: ''

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: '1.5.7'

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}

