name: CD - Terraform Deploy (manual)

on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: 'Docker image tag (e.g. full commit SHA)'
        required: true
        default: 'latest'
      docker_repo:
        description: 'Docker repo (username/strapi-app) — override if needed'
        required: false
        default: ''

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: '1.5.7'

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Initialize Terraform
        run: |
          cd terraform
          terraform init -input=false

      - name: Terraform plan
        run: |
          cd terraform
          # Set docker_repo variable
          DOCKER_REPO="${{ inputs.docker_repo }}"
          if [ -z "$DOCKER_REPO" ]; then
            DOCKER_REPO="${{ secrets.DOCKERHUB_USERNAME }}/strapi-app"
          fi

          terraform plan \
            -var="image_tag=${{ inputs.image_tag }}" \
            -var="ssh_public_key=${{ secrets.SSH_PUBLIC_KEY }}" \
            -var="docker_repo=$DOCKER_REPO" \
            -out=plan.tfplan
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}

      - name: Terraform apply
        run: |
          cd terraform
          terraform apply -input=false -auto-approve plan.tfplan

      - name: Print public IP
        run: |
          cd terraform
          terraform output -raw public_ip

